DOCS_TITLE = "BulkMail"
DOCS_VERSION = "1.0"
AMQP_URL = "amqp://guest:guest@rabbit-mq/"
EMAIL_PERSONALIZATION_QUEUE = "EMAIL_PERSONALIZATION_QUEUE"
MOCK_SUCCESS_RATE = 0.05
PROCESS_AND_SEND_EMAIL_RETRY_COUNT = 3
REDIS_HOST = "redis"
