version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bulk-email-server
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - rabbit-mq
    privileged: true
  worker:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bulk-email-worker
    command: ["celery", "-A", "worker.main", "worker", "--loglevel=info", "--queues=EMAIL_PERSONALIZATION_QUEUE", "--concurrency=1"]
    depends_on:
      - redis
      - rabbit-mq
  redis:
    image: redis
    container_name: bulk-email-redis
    ports:
      - '6379:6379'
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: bulk-email-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
